[project]
name = "ai-dev-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "black>=25.11.0",
    "django>=5.2.8",
    "pre-commit>=4.4.0",
    "ruff>=0.14.5",
]
